# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laura Janelle
email: info@laurajanelle.com
description: Fashion accessories for the gift market
url: https://www.laurajanelle.com


#baseurl: "/cousin-op"

# Footer settings
footer: Laura Janelle

# Build settings
markdown: kramdown
permalink: pretty
